package com.purewave.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Represents a project entity to be stored in a MongoDB collection.
 * This class holds the essential data related to a project, including
 * unique identifiers, user association, title, and references to audio resources.

 * The Project class is primarily managed and used within the context of the ProjectController
 * and ProjectService to perform CRUD operations and handle project-related business logic.

 * Fields:
 * - id: A unique identifier for the project, automatically generated by MongoDB.
 * - accessId: A unique access key generated for the project.
 * - userId: The identifier of the user who owns the project, generally corresponding to an authenticated user's email.
 * - title: Title or name of the project, set or updated by the user.
 * - dryAudio: A reference or path to the dry (unaltered) audio associated with the project.
 * - wetAudio: A reference or path to the wet (processed) audio associated with the project.
 */
@Document(collection = "projects")
@Data
public class Project {

    @Id
    private String id;
    private String accessId;
    private String userId;
    private String title;
    private String dryAudio;
    private String wetAudio;
}
